### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [NinaOConnell/teacozy#3]
Meets Expectations

This was very well done it looks just like the spec (minus the gap at the top). One of the main focuses of this project is to practice flex which you did an awesome job of. I left an issue open to get the gap at the top fix, which was my only nit-pick of this project.  Next try to challenge yourself by adding a menu, if you need idea try using themeforest.com or your local cafe! Keep up the good work. You might also want a contact form, you can find a easy example to follow on w3schools.com

**Comment by NinaOConnell** [comment]
Awesome! Thank you very much for the additional links and feedback.
